language: php
php:
  - "5.5"
  - "5.4"
before_script:
  ## Composer
  - composer install
  ## travis configuration
  - cp app/config/config.ini-travis app/config/config.ini
script: php vendor/atoum/atoum/bin/atoum -d tests/units/
notifications:
  irc:
    channels:
      - "irc.mozilla.org#transvision"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
      - "%{repository} ; %{commit} (%{author}) : %{message} "
      - "Build details: %{build_url} ; changes: %{compare_url}"
